### ISSUE TITLE
virustotal warning

### ISSUE THREAD

**Issue by networkpadawan** [bamtan/PokemonGoAnywhere#1]
Virustotal signs PokemonGoAnywhere.dylib having Trojan-Spy.IOS.KeyRaider?

**Comment by ExodusGen** [comment]
Does this still work with Pokemon Go ver. 1.0.3?

**Comment by bamtan** [comment]
That is very strange. From my research the KeyRaider malware hooks into MobileSubstrate, something that isnt possible with a jailed device, so you should be safe.

**Comment by bamtan** [comment]
I'm not sure if this method works with v1.0.3, again, try the PPSideloaded method, or check out http://reddit.com/r/IPAhub

**Comment by ExodusGen** [comment]
It works thanks

**Comment by bamtan** [comment]
No problem, if you have any other questions feel free to open your OWN issue, rather than jumping onto someone elses ;)
