### ISSUE TITLE
new updated .dylib

### ISSUE THREAD

**Issue by natedkin** [bamtan/PokemonGoAnywhere#2]
Is there anyway to do it with the new .dylib? this is the updated tweak  PokemonGoAnwhere 1.2r-32 from williamlcobb repo on cydia but when I try to use this method on my unjailbroken device, the app seems to crash at launch. 

[PokemonGoAnywhere.dylib.zip]
(https://github.com/bamtan/PokemonGoAnywhere/files/378688/PokemonGoAnywhere.dylib.zip)

**Comment by bamtan** [comment]
Did you get this .dylib.zip directly from William Cobbs repo?

**Comment by natedkin** [comment]
Of course.

**Comment by natedkin** [comment]
I ended up side loading the Pokemon Go ++ from iphonecake.

**Comment by bamtan** [comment]
Ah, my bad. 

The PokemonGoAnywhere dylib here has been modified to support sideloading, so you may want to contact the dev about modifying 1.2r-32 to be able to sideload. I believe the dev & eni9889 are working together with Poke++, though. So features should be implemented on there.
